import { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Navbar from '@/src/global/Navbar'
import Search from '@/src/global/Search'
import Category from '@/src/home/Category'
import { filmCategories } from '@/assets/film_info'
import Footer from '@/src/global/Footer'

export default function Home() {

  return (
    <>
      <Head>
        <title>Moviemanic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/movie-projector.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.col1}>
          <Navbar />
        </div>
        <div className={styles.col2}>
          <div className={styles.content}>
            <Search />
            {
              filmCategories.map(c =>
                <Category
                  key={c.id}
                  categoryName={c.name}
                  showType={c.type}
                  isTrending={c.isTrending}
                  fetch_path={c.fetch_path}
                />
              )
            }
          </div>
        </div>
      </main>
      <Footer />
    </>
  )
}

