import Head from 'next/head'
import Image from 'next/image'
// import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import Navbar from '@/src/Navbar'
import Search from 'src/Search'
import Category from '@/src/Category'


// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  let movieCategoryTypes = ['Trending', 'Popular', 'Now Playing', 'Upcoming', 'Top Rated']
  let tvShowCategoryTypes = ['Trending', 'Popular', 'Airing Today', 'On Air', 'Top Rated']

  return (
    <>
      <Head>
        <title>Moviemanic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/movie-projector.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <div>
          <Search />
          {
            movieCategoryTypes.map((n, i) => 
              <Category key={i} categoryName={n} show='movie'/>
            )
          }
          {
            tvShowCategoryTypes.map((n, i) => 
              <Category key={i} categoryName={n} show='tv series'/>
            )
          }
          
        </div>
      </main>
    </>
  )
}
